# Generated by Django 2.2.7 on 2020-04-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emptyroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.CharField(max_length=254)),
                ('location', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Occupied', 'Occupied'), ('Empty', 'Empty')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Emptyroom',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=150)),
                ('mdate', models.DateField()),
                ('mtime', models.TimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('BIT', 'BIT'), ('BBIT', 'BBIT'), ('BCS', 'BCS'), ('BCSF', 'BCSF')], max_length=254)),
                ('unit', models.CharField(max_length=254)),
                ('rooms', models.CharField(max_length=254)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Occupied', 'Occupied'), ('Empty', 'Empty')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Lecturer',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.CharField(max_length=254)),
                ('location', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Occupied', 'Occupied'), ('Empty', 'Empty')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Room',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('BIT', 'BIT'), ('BBIT', 'BBIT'), ('BCS', 'BCS'), ('BCSF', 'BCSF')], max_length=254)),
                ('year_of_study', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=254)),
                ('rooms', models.CharField(max_length=254)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Occupied', 'Occupied'), ('Empty', 'Empty')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Student',
                'ordering': ['-created'],
            },
        ),
    ]
