# Generated by Django 2.2.7 on 2020-06-24 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_cruduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AddField(
            model_name='student',
            name='mtime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='course',
            field=models.CharField(choices=[('BIT', 'BIT'), ('BBIT', 'BBIT'), ('BCS', 'BCS'), ('BCSF', 'BCSF'), ('BMC', 'BMC')], max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('BIT', 'BIT'), ('BBIT', 'BBIT'), ('BCS', 'BCS'), ('BCSF', 'BCSF'), ('BMC', 'BMC')], max_length=254),
        ),
    ]
